apiVersion: v1
kind: Service
metadata:
  name: simplepythonapp-service
spec:
  selector:
    app: simplepythonapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
